title : Timothee Cloup-Martin
logo: "./img/fotor-2026010318485.png"
theme: jekyll-theme-minimal
show_downloads: false

description: >
  ## Data Scientist Junior
  
  âœ‰ï¸ [timothee.cloupmartin@gmail.com](mailto:timothee.cloupmartin@gmail.com)  
  ğŸ“ +33 6 48 88 11 36  
  ğŸ”— [LinkedIn](https://fr.linkedin.com/in/timoth%C3%A9e-cloup-martin-b8b203252)

github_username: timotheeCloup
